# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e92d9bacb5680fe933dc0bf559f7451d38c7c48312e9dbe281e18cb29b3b62752216eed52a03b6cb33cd58f703fa7b38bd3360728c6751b575470e95958533a

test:
  secret_key_base: 79621074fdafd79d13d65bb3a4e6bea0413a1feb3d041c15954854e666683e3c4bd8884968399f4030541b1a06863bdb82b85f1def3ca9d90dc4063388907825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
